- src/DI/Container.php
- src/DI/ContainerBuilder.php
- tests/DI/Compiler.services.tags.phpt
- tests/DI/ContainerBuilder.aliases2.phpt
At the moment there is no sensible way how to rename a service without massive BC break, that's why some of the "Nette" services use prefixes, some not etc. This PR tries to fix this by adding support for service aliases to `ContainerBuilder`.
Open question is whether or not to automatically trigger deprecation warning when the old name (=alias) is used instead of the new one.
> ContainerBuilder: Add support for aliasing service definitions

- src/DI/CompilerExtension.php
- src/DI/Extensions/DecoratorExtension.php
- tests/DI/CompilerExtension.validateConfig.phpt
I have a problem with validateConfig() usage, it is not understandable. Typical usecase is:
```php
$config = $this->getConfig($this->defaults);
$this->validateConfig($this->defaults, $config);
```
In this case `$config` is unnecessary, so you can write: 
```php
$config = $this->getConfig($this->defaults);
$this->validateConfig($this->defaults);
```
It seems like WTF. Defaults are passed to `validateConfig` for the same reasons as to `getConfig()`, but it is really weirg. 
What about this simplification?
```php
$config = $this->validateConfig($this->defaults);
```
Or
```php
$config = $this->getValidatedConfig($this->defaults);
```
> CompilerExtension::validateConfig() returns combined array

- src/DI/ContainerBuilder.php
- tests/DI/ContainerBuilder.basic.phpt
Attempt to solve nette/nette#1279
`ContainerBuilder:.formatPhp()` recognizes '\@' at the beginning of string value as escaped '@'.
What do you think about this, is this a reasonable approach? Shall I go ahead and write tests for it?
> ContainerBuilder: implement escaping of '@' at the beginning of string

- src/DI/Compiler.php
- tests/DI/Compiler.extension.phpt
Pro předpřipravenou strukturu configu jsou často potřebné prázdné sekce (security, atd..), které nastavujete až v průběhu vývoje. V nette 2.2.x to bylo možné.
> Compiler: extension without parameters is allowed now

- src/DI/ContainerBuilder.php
- src/DI/PhpReflection.php
- tests/DI/Compiler.generatedFactory.returnTypes.phpt
- tests/DI/Compiler.generatedFactory.scalarParameters.phpt
- tests/DI/ContainerBuilder.factory.resolveBuiltinTypes.php5.phpt
- tests/DI/ContainerBuilder.factory.resolveBuiltinTypes.php7.phpt
- tests/DI/ContainerBuilder.factory.resolveClass.returnTypes.phpt
- tests/DI/files/compiler.generatedFactory.returnTypes.neon
- tests/DI/files/compiler.generatedFactory.scalarParameters.neon
**Depends on https://github.com/nette/php-generator/pull/11**
- feature
- documentation - not needed
- BC break - no
Adds support for PHP 7 syntax and features:
- factories can now use return type declarations instead of the `@return` annotation
- scalar type hints can be used in parameters of the factory interfaces
> Support for PHP7 return types and scalar parameters for factories

- tests/php-unix.ini
php-unix.ini: added tokenizer extension
Tokenizer is needed under default OpenSuSE installation of Apache 2
>  Added tokenizer module for testing under unix

- src/DI/ContainerBuilder.php
- tests/DI/ContainerBuilder.aliases2.phpt
This feature request is similar to the function `removeDefinition` in `ContainerBuilder`. It can be useful to remove aliases as well. For example I am trying to do hot-reload already registered extensions inside of another extensions to add additional configuration. Unfortunately it's not possible without removing aliases (or maybe I don't know how). See [this use case](https://gist.github.com/mrtnzlml/21690953afb9dfad1824#file-compilerextension-php-L47).
> ContainerBuilder::removeAlias() removes aliases

- src/DI/ContainerBuilder.php
- tests/DI/Compiler.generatedFactory.phpt
Purpose: throw an Exception when you have typo in the name of parameter in factory method (or constructor of factory product).
Related: #60
> Check for unused parameter when generating factory

- src/DI/Compiler.php
- src/DI/Helpers.php
- tests/DI/Compiler.parseServices.namespace.phpt
- tests/DI/files/compiler.parseServices.namespace.neon
ref nette/web-content#377
cc @Majkl578 @greeny
> Compiler::parseServices: allow prefixing service name in the config

- src/DI/Compiler.php
- src/DI/ContainerBuilder.php
- src/DI/ServiceDefinition.php
- tests/DI/ContainerBuilder.autowiring.types.phpt
~~All services are autowired. `setAutowired(TRUE)` means that service is preferred, `setAutowired(FALSE)` means that is autowired too, but not preferred (yes, name `setAutowired(FALSE)` is weird here, but this is just experiment).~~
Only services that are excluded via `$excludedClasses` are not autowired.
~~Now you can create services FileStorage (autowired: on) and DevNullStorage (autowired: off) and access the first one via `getByType('IStorage') and second one via `getByType('DevNullStorage')`.~~
I tried [a different approach](https://github.com/nette/di/pull/84#issuecomment-217701242)
> Alternative autowiring approach [WIP]

- src/DI/Compiler.php
It is named parseServices, because it parses 'service' in config, but it is public method and therefore should have more descriptive names. `addDefinitions()`? `loadDefinitions()`? `loadDefinitionsFromConfig()`?
> Compiler: parseServices() and parseService() renamed to ??? [WIP]

- src/DI/PhpReflection.php
- tests/DI/PhpReflection.getParameterType.php71.phpt
Nullable parameter types are prefixed by `?` in Reflection in PHP 7.1 which causes that Nette autowiring doesn't work. Even though this behaviour has changed many times in PHP 7.1 ( https://github.com/php/php-src/commit/622d2f41d1cdb597f4fafecaaacf66e238742bd4 , https://github.com/php/php-src/commit/8855a2ce76e8bfba1d2eea1345c765fde7a9a441 , https://github.com/php/php-src/commit/f4e68a3968429757719c600ce16913ab09539f0d ) this fix uses new preferred way ReflectionNamedType::getName() which looks pretty stable.
> PhpReflection::getParameterType() can handle PHP 7.1 nullable types

- src/DI/Config/Loader.php
- tests/DI/Loader.include.phpt
- tests/DI/files/loader.includes.child.php
- tests/DI/files/loader.includes.grandchild.neon
I'm developing a system-wide application. Many `neon` configurations files in `/etc/app` and `/usr/lib/app/module-xxx/config.neon`. Would be more comfortable to work with absolute paths.
> Config\Loader: allow absolute paths in includes section

- src/DI/ContainerBuilder.php
- tests/DI/ContainerBuilder.getDefinitionByType.phpt
- bug fix? no #130
- new feature? yes
- BC break? no
All is described in the issue: #130 
Behavior is compatible with with `getDefiniton()` - exception is thrown when not found.
This method is called in cases where Definition is required.
> [ContainerBuilder] getDefinitionByType() method added

- src/DI/Compiler.php
- tests/DI/Compiler.configOverride.phpt
- bug fix? yes
- new feature? yes
- BC break? yes
When you have multiple config files, things like alternation does not work. 
Or if you have `services: [Foo]` (without `class` key) in one config and you try to add `setup` in another config, it fails.
This may cause a bc break when a service definition in the first config is incomplete.
> Compiler: loadDefinitions is called for each config separately

- src/DI/PhpGenerator.php
- tests/DI/Compiler.generatedFactory.returnTypes.phpt
- tests/DI/files/compiler.generatedFactory.returnTypes.neon
- bug fix? yes
- BC break? no
because php does not support return type covariance
> generated factories: fix return type

- src/DI/ServiceDefinition.php
- tests/DI/ServiceDefinition.phpt
- bug fix? no   
- BC break? yes
`class` vs `factory` should be better distinguished, it is difficult to merge more configs where these options are mixed. Related to #39
> ServiceDefinition::setClass() parameter $args is deprecated (BC break)

- src/DI/Config/Loader.php
- bug fix? yes
- BC break? no
Including a config in the following way doesn't work
```yaml
includes:
- phar://phpstan.phar/vendor/phpstan/phpstan-doctrine/extension.neon
```
> fixed including of paths with scheme in config loader

- src/DI/ContainerBuilder.php
- tests/DI/ContainerBuilder.autowiring.novalue.phpt
- tests/DI/ContainerBuilder.error.phpt
- tests/DI/ContainerBuilder.factory.error.phpt
- bug fix? no
- BC break? no
In case of malformed dependencies I got message such `"Service '94': ..."`. Now I get `"Service '94' (type of App\Presenter\HomePagePresenter): ..."`
> In case of malformed dependencies provide type hint for calling service

- src/DI/Extensions/DIExtension.php
- bug fix? no
- BC break? maybe
---
I've dropped unused configuration option `accessors`.
> DIExtension: drop unused accessors

- src/DI/Extensions/DIExtension.php
- tests/DI/DIExtension.run.phpt
- bug fix  
- BC break? no
Following code 
```yaml
services:
- {factory: stdClass, tags: [run]}
```
causes TypeError: ` TypeError: Argument 1 passed to Nette\DI\Container::getService() must be of the type string, integer given`
> DIExtension: service name tagged with run cast to string

- src/DI/ContainerBuilder.php
- tests/DI/Compiler.generatedFactory.polymorphism.phpt
- tests/DI/files/compiler.generatedFactory.polymorphism.neon
- new feature #174 
- BC break? no
> ContainerBuilder:resolveImplement supports polymorphism

- src/DI/Container.php
- bug fix
- BC break? no
Container::getByType really returns null (previously "returned" void).
> Container::getByType fixed phpdoc return typehint

- src/DI/ContainerBuilder.php
- bug fix? yes
- BC break? no
Added link to previous exception when service creation failed due to reflection exception - because for example class not found.
> ContainerBuilder: set caused by exception

- src/DI/Autowiring.php
- tests/DI/ContainerBuilder.autowiring.type[].phpt
Autowiring of array of `Service` this way: (BC break)
```php
class Foo
{
public $services;
/**
* @param Service[] $services
*/
public function __construct(array $services)
{
$this->services = $services;
}
}
```
> autowiring via Service[] (WIP)

- src/DI/Config/Processor.php
- bug fix
- BC break? no
Hi, I have found bug in beta version. When you try to use config like shown below, it throws "User Deprecated" error.
```neon
services:
- 
implement: SomeInterface
arguments:
foo: bar
```
> Processor: replaced call of depracated getFactory() method on definition

- src/DI/Config/Processor.php
```
services:
router: 
type: class
```
will not override parent `factory`
> Compiler: definition of 'type' will not overide 'factory' of parent service 

- src/DI/Compiler.php
- Bug fix
- BC break? no
Decorator extension needs to be resolved last (eg. after Search extension) in order to find all possible matching services.
Solves my issue where decorator doesn't decorate services found using Search extension.
> Added Decorator extension to $last

- src/Bridges/DITracy/ContainerPanel.php
- src/DI/PhpGenerator.php
- bug fix
- BC break? no
Solve:
```
------ -------------------------------------- 
Line   DI/PhpGenerator.php                   
------ -------------------------------------- 
99     Variable $name might not be defined.  
------ -------------------------------------- 
```
> PhpGenerator: $name might not be defined

- src/DI/Helpers.php
- bug fix
- BC break? yes
Solve error:
```
------ --------------------------------------------------------- 
Line   DI/Helpers.php                                           
------ --------------------------------------------------------- 
157    Call to an undefined method Reflector::getDocComment().  
157    Call to an undefined method Reflector::getDocComment().  
------ --------------------------------------------------------- 
```
> Helpers: Annotation for hinting ->getDocComment().

- src/DI/Extensions/InjectExtension.php
- bug fix
- BC break? no
Fix type error and if condition order:
```
------ ---------------------------------------------------------- 
Line   DI/Extensions/InjectExtension.php                         
------ ---------------------------------------------------------- 
37     Right side of && is always true.                          
61     Parameter #4 $container of static method                  
Nette\DI\Extensions\InjectExtension::checkType() expects  
Nette\DI\Container|Nette\DI\Resolver|null,                
Nette\DI\ContainerBuilder|null given.                     
------ ---------------------------------------------------------- 
```
> InjectExtension: Fix type hint and always executed if.

- src/DI/Definitions/Definition.php
- bug fix
- BC break? no
Fix error:
```
------ ------------------------------------------------------------------- 
Line   DI/Definitions/Definition.php                                      
------ ------------------------------------------------------------------- 
159    Property Nette\DI\Definitions\Definition::$name (string) does not  
accept null.                                                       
------ ------------------------------------------------------------------- 
```
> Name can accept null.

- src/DI/Resolver.php
- bug fix
- BC break? no
Fix and basic reimplementation for define type hints in comment section and little code reorganization.
```
------ --------------------------------------------------------------------- 
Line   DI/Resolver.php                                                      
------ --------------------------------------------------------------------- 
117    Call to an undefined method ReflectionFunctionAbstract::isPublic().  
117    Variable $refClass might not be defined.                             
117    Variable $reflection might not be defined.                           
118    Call to an undefined method ReflectionFunctionAbstract::isStatic().  
118    Variable $reflection might not be defined.                           
122    Variable $reflection might not be …
```
> Resolver: Fix undefined and never called spaces.

- src/DI/Extensions/ExtensionsExtension.php
- bug fix
- BC break? no
Fix type hint and solve error:
```
------ --------------------------------------------------------------------- 
Line   DI/Extensions/ExtensionsExtension.php                                
------ --------------------------------------------------------------------- 
34     Parameter #2 $extension of method Nette\DI\Compiler::addExtension()  
expects Nette\DI\CompilerExtension, object given.                    
------ --------------------------------------------------------------------- 
```
> ExtensionsExtension: Fix type hint of RC

- src/DI/Extensions/SearchExtension.php
- new feature  #196 
- BC break? no
This PR extends SearchExtension to be able to search for interfaces and create factory definitions from them.
WIP is added due to some duplicate code that needs to be refactored.
> SearchExtension - ability to create factory definitions from interfaces

- src/DI/Resolver.php
- bug fix
- BC break? no
In case of neon file:
```yaml
services:
tagManagerAccessor:
factory: Namespace\TagManagerAccessor
```
Nette throws user unfriendly exception:
`Class 'Namespace\TagManagerAccessor' not found.`
I think if the class does not exist, but the interface does, Nette should throw more user-friendly exception like:
`Service 'tagManagerAccessor': Class 'Namespace\TagManagerAccessor' not found. Interface 'Namespace\TagManagerAccessor' can not be used in 'factory' section as service.`
Thanks.
> Resolver: better exception message

- src/DI/Extensions/SearchExtension.php
- bug fix
- BC break? no
Throw exception when class is not autoloaded.
For example I set find directory to project root, but Robot loaded is mapping `app` dir only.
> SearchExtension: Exception when class is not autoloaded.

- src/DI/Extensions/DecoratorExtension.php
Maybe change `!class_exists($type)` to `!class_exists($type) && !interface_exists($type)`, but I don't use decorator interfaces
> DecoratorExtension: throws exception if class not exists

- src/Bridges/DITracy/ContainerPanel.php
- bug fix
- BC break? no
Better sorting strings containing integers.
Name | Autowired | Service
-- | -- | --
application.1 | yes | App\MyService
application.10 | yes | App\FooService
application.11 | yes | App\BarService
application.12 | no | App\FooBarService
application.2 | yes | App\Foo
application.3 | yes | App\Bar
Name | Autowired | Service
-- | -- | --
application.1 | yes | App\MyService
application.2 | yes | App\FooService
application.3 | yes | App\BarService
application.4 | no | App\FooBarService
application.5 | yes | App\Foo
application.6 | yes | App\Bar
> Better sorting for human eyes

- src/DI/Container.php
Without specifying the upper bound, PHPStan fails to resolve the return type.
> fix Container::getByType() compatibility with PHPStan

- src/DI/Resolver.php
- tests/DI/ContainerBuilder.autowiring.type[].phpt
- bug fix / new feature?
New feature
[Autowiring a collection of services](https://doc.nette.org/en/dependency-injection/autowiring#toc-collection-of-services) already supports `@param Type[] $foo` and `@param array<int, Type>`, and using `@param list<Type> $foo` is basically the same thing in this case. For some people, like me, using `list<>` better indicates that the key of the array can be ignored (or can be assumed sequential).
- BC break? yes/no
no
- doc PR: nette/docs#???  
https://github.com/nette/docs/pull/1031
> Support `list<Type>` syntax for autowiring a collection of services

- src/DI/Extensions/ServicesExtension.php
- tests/DI/Compiler.generatedLocator.phpt
- bug fix / new feature?   new feature
- BC break? no
- doc PR: nette/docs#???  
In example I used classes from my library, if you want to try, let's use `composer require h4kuna/number-format:dev-mater`, but i think it is not necessary.
I want to define custom collection of formats
```neon 
services:
format.date:
factory: h4kuna\Format\Date\Formatters\DateTimeFormatter('j.n.Y')
autowired: false
format.time:
factory: h4kuna\Format\Date\Formatters\DateTimeFormatter('H:i:s')
autowired: false
date.formats: h4kuna\Format\Date\FormatsAccessor(
date: @format.date
time: @format.time
)
latte.latteFactory:
setup:
- addFilter('date', @date.formats::get('date'))
- addFilter('time', @date.formats::get('time'))
```
The original way is too chatty, the patch allow
```neon 
services:
date.formats: …
```
> ServicesExtension: locator support Statement

- tests/DI/Compiler.parameters.phpt
`DateTimeImmutable` throws user notice since version 3.2.0:
```
E_USER_NOTICE: Nette DI: suspicious dumping of objects DateTimeImmutable when generating the container
```
PR contains failing test.
> Test for "Nette DI: suspicious dumping of objects DateTimeImmutable when generating the container"
